json.id exercise.id
json.user_id exercise.user_id 
json.routine_id exercise.routine_id 
json.reps exercise.reps 
json.sets exercise.sets 
json.name exercise.name
json.description exercise.description
json.resistance exercise.resistance
json.image_url exercise.image_url